### ISSUE TITLE
Metadata on US-traded companies

### ISSUE THREAD

**Issue by jjviton** [PacktPublishing/Machine-Learning-for-Algorithmic-Trading-Second-Edition_Original#12]
Hi all,

I writing here reporting an issue I am facing dataGeneration stage.
this part of the code fails. It seems Nasdaq does not allow downloading...

**url = 'https://nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange={}&render=download'
exchanges = ['NASDAQ', 'AMEX', 'NYSE']
df = pd.concat([pd.read_csv(url.format(ex)) for ex in exchanges]).dropna(how='all', axis=1)**

**Comment by stefan-jansen** [comment]
Please use [this](https://github.com/stefan-jansen/machine-learning-for-trading) repository which is regularly updated and has information that addresses your problem.
