### ISSUE TITLE
nightmare

### ISSUE THREAD

**Issue by johanbech** [PacktPublishing/Machine-Learning-for-Algorithmic-Trading-Second-Edition_Original#14]
why is so hard just to start?
Environment installation is nightmare, still not work now 'data' is not exit. Too bad  for writing so big book and make hard to start.

**Comment by stefan-jansen** [comment]
Please use this repo to raise issues: https://github.com/stefan-jansen/machine-learning-for-trading

I'm happy to help but need some specifics about what kind of problems you are facing.

Moreover, this should not be complicated. You do not need to install everything for the book at once. Just create a virtual environment and install the few packages you need for whatever you want to run.
