### ISSUE TITLE
Typo in the notebook

### ISSUE THREAD

**Issue by khuyentran1401** [PacktPublishing/Machine-Learning-for-Algorithmic-Trading-Second-Edition_Original#2]
In the notebook /14_working_with_text_data/03_document_term_matrix.ipynb cell 19,  it should be `results_path` instead of `reslts_path`.

**Comment by stefan-jansen** [comment]
Fixed in the master repo `https://github.com/stefan-jansen/machine-learning-for-trading`; this should just be a fork.
