### ISSUE TITLE
I do not see train predictions generated in the notebook alphalens_signal_quality

### ISSUE THREAD

**Issue by zmarozas** [PacktPublishing/Machine-Learning-for-Algorithmic-Trading-Second-Edition_Original#6]
Hello,
In  chapter 11  notebook 07_backtesting_with_zipline.ipynb it states that:
"We generate the train predictions in the notebook alphalens_signal_quality and the test predictions in the notebook random_forest_return_signals." 

However I do not see code for generating train predictions. Am I missing something?
Regards,
Zilvinas

**Comment by stefan-jansen** [comment]
Please refer to [this](https://github.com/stefan-jansen/machine-learning-for-trading) repository.
